AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  EnabledByDefault: true
  Exclude:
    - bin/**/*
    - vendor/**/*
  ExtraDetails: true
  NewCops: enable
  TargetRubyVersion: 4.0
  UseCache: true

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-capybara
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-sequel
  - rubocop-thread_safety

inherit_gem:
  docquet:
    - config/cops/bundler.yml
    - config/cops/capybara.yml
    - config/cops/gemspec.yml
    - config/cops/layout.yml
    - config/cops/lint.yml
    - config/cops/metrics.yml
    - config/cops/naming.yml
    - config/cops/performance.yml
    - config/cops/rake.yml
    - config/cops/rspec.yml
    - config/cops/security.yml
    - config/cops/sequel.yml
    - config/cops/style.yml
    - config/cops/thread_safety.yml

inherit_from: .rubocop_todo.yml

Lint/EmptyBlock:
  Exclude:
    - spec/factories/user.rb

RSpec/SpecFilePathFormat:
  CustomTransform:
    PastaAtlas: ""

Style/Documentation:
  Exclude:
    - app/action.rb
    - app/actions/**/*.rb
    - app/operation.rb
    - app/operations/**/*.rb
    - app/relations/**/*.rb
    - app/repos/**/*.rb
    - app/structs/**/*.rb
    - app/views/helpers.rb
    - config/routes.rb
    - config/settings.rb
    - lib/pasta_atlas/types.rb

Style/DocumentationMethod:
  Exclude:
    - app/actions/**/*.rb
    - app/operations/**/*.rb
    - app/relations/**/*.rb
    - app/repos/**/*.rb
