[env]
_.path = ["bin", "node_modules/.bin"]

[tasks.default]
depends = ["dev"]

[tasks.dev]
depends = ["web", "assets", "islands"]

[tasks.web]
run = "bundle exec hanami server"

[tasks.assets]
run = "bundle exec hanami assets watch"

[tasks.islands]
run = "npm run dev:islands"
