[env]
_.file = [".env", ".env.development", ".env.development.local", ".env.local"]
_.path = ["bin", "node_modules/.bin"]

[tools]
aws-cli = "latest"
gitleaks = "latest"
ruby = "4"
sops = "latest"
terraform = "1.15"
tflint = "0.62"

[tasks.default]
depends = ["dev"]

[tasks.dev]
depends = ["web", "assets", "islands", "floci", "sqs-worker"]

[tasks.web]
run = "bundle exec hanami server"

[tasks.assets]
run = "bundle exec hanami assets watch"

[tasks.islands]
run = "npm run dev:islands"

[tasks.floci]
run = "docker compose up"

[tasks.sqs-worker]
run = "bundle exec rake sqs:worker"
