[env]
_.file = [".env", ".env.development", ".env.development.local", ".env.local"]
_.path = ["bin", "node_modules/.bin"]

[tools]
terraform = "1.15.1"
"aqua:terraform-linters/tflint" = "0.62.0"
gitleaks = "latest"

[tasks.default]
depends = ["dev"]

[tasks.dev]
depends = ["web", "assets", "islands", "floci"]

[tasks.web]
run = "bundle exec hanami server"

[tasks.assets]
run = "bundle exec hanami assets watch"

[tasks.islands]
run = "npm run dev:islands"

[tasks.floci]
run = "docker compose up"
