--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: credentials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credentials (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    provider text NOT NULL,
    uid text NOT NULL,
    data jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: credentials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credentials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credentials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: upload_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.upload_events (
    id bigint NOT NULL,
    upload_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT event_type_values CHECK ((event_type = ANY (ARRAY['pending'::text, 'complete'::text, 'failed'::text])))
);


--
-- Name: current_upload_statuses; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.current_upload_statuses AS
 SELECT DISTINCT ON (upload_id) upload_id,
    event_type AS status,
    occurred_at
   FROM public.upload_events
  ORDER BY upload_id, occurred_at DESC, id DESC;


--
-- Name: generations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.generations (
    id bigint NOT NULL,
    ulid character varying(26) NOT NULL,
    map_id bigint NOT NULL,
    mapshot_unique_id text NOT NULL,
    tick bigint NOT NULL,
    metadata_s3_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    storage_bytes bigint
);


--
-- Name: generations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.generations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.generations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: maps; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.maps (
    id bigint NOT NULL,
    ulid character varying(26) NOT NULL,
    user_id bigint NOT NULL,
    mapshot_map_id text NOT NULL,
    savename text DEFAULT ''::text NOT NULL,
    name text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: maps_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.maps ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    filename text NOT NULL
);


--
-- Name: upload_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.upload_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.upload_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: uploads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.uploads (
    id bigint NOT NULL,
    ulid character varying(26) NOT NULL,
    generation_id bigint NOT NULL,
    total_image_count integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: uploads_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.uploads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.uploads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_preferences (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    timezone text,
    locale text,
    relative_timestamps boolean DEFAULT false NOT NULL
);


--
-- Name: user_preferences_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_profiles (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    display_name text,
    avatar_s3_key text
);


--
-- Name: user_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    name text NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credentials credentials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credentials
    ADD CONSTRAINT credentials_pkey PRIMARY KEY (id);


--
-- Name: generations generations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT generations_pkey PRIMARY KEY (id);


--
-- Name: maps maps_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_pkey PRIMARY KEY (id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (filename);


--
-- Name: upload_events upload_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_events
    ADD CONSTRAINT upload_events_pkey PRIMARY KEY (id);


--
-- Name: uploads uploads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_pkey PRIMARY KEY (id);


--
-- Name: user_preferences user_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (id);


--
-- Name: user_profiles user_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: credentials_provider_uid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX credentials_provider_uid_index ON public.credentials USING btree (provider, uid);


--
-- Name: credentials_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX credentials_user_id_index ON public.credentials USING btree (user_id);


--
-- Name: generations_expires_at_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX generations_expires_at_index ON public.generations USING btree (expires_at);


--
-- Name: generations_map_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX generations_map_id_index ON public.generations USING btree (map_id);


--
-- Name: generations_map_id_mapshot_unique_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX generations_map_id_mapshot_unique_id_index ON public.generations USING btree (map_id, mapshot_unique_id);


--
-- Name: generations_ulid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX generations_ulid_index ON public.generations USING btree (ulid);


--
-- Name: maps_ulid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX maps_ulid_index ON public.maps USING btree (ulid);


--
-- Name: maps_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX maps_user_id_index ON public.maps USING btree (user_id);


--
-- Name: maps_user_id_mapshot_map_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX maps_user_id_mapshot_map_id_index ON public.maps USING btree (user_id, mapshot_map_id);


--
-- Name: upload_events_upload_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX upload_events_upload_id_index ON public.upload_events USING btree (upload_id);


--
-- Name: uploads_generation_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uploads_generation_id_index ON public.uploads USING btree (generation_id);


--
-- Name: uploads_ulid_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uploads_ulid_index ON public.uploads USING btree (ulid);


--
-- Name: user_preferences_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_preferences_user_id_index ON public.user_preferences USING btree (user_id);


--
-- Name: user_profiles_user_id_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_profiles_user_id_index ON public.user_profiles USING btree (user_id);


--
-- Name: users_name_index; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_name_index ON public.users USING btree (name);


--
-- Name: credentials credentials_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credentials
    ADD CONSTRAINT credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: generations generations_map_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.generations
    ADD CONSTRAINT generations_map_id_fkey FOREIGN KEY (map_id) REFERENCES public.maps(id) ON DELETE CASCADE;


--
-- Name: maps maps_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.maps
    ADD CONSTRAINT maps_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: upload_events upload_events_upload_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.upload_events
    ADD CONSTRAINT upload_events_upload_id_fkey FOREIGN KEY (upload_id) REFERENCES public.uploads(id) ON DELETE CASCADE;


--
-- Name: uploads uploads_generation_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.uploads
    ADD CONSTRAINT uploads_generation_id_fkey FOREIGN KEY (generation_id) REFERENCES public.generations(id) ON DELETE CASCADE;


--
-- Name: user_preferences user_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_preferences
    ADD CONSTRAINT user_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_profiles user_profiles_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


SET search_path TO "$user", public;

INSERT INTO schema_migrations (filename) VALUES
('20260427133009_create_users.rb'),
('20260427133021_create_user_profiles.rb'),
('20260427133022_create_credentials.rb'),
('20260427133023_create_maps.rb'),
('20260427133024_create_generations.rb'),
('20260427133025_create_uploads.rb'),
('20260501170231_add_display_name_to_user_profiles.rb'),
('20260501180000_add_timezone_to_user_profiles.rb'),
('20260502133550_add_avatar_s3_key_to_user_profiles.rb'),
('20260504120000_add_expires_at_to_generations.rb'),
('20260504130000_create_user_preferences.rb'),
('20260504140000_remove_timezone_from_user_profiles.rb'),
('20260523000000_add_relative_timestamps_to_user_preferences.rb'),
('20260527000000_redesign_upload_events.rb'),
('20260605000000_make_timezone_nullable_in_user_preferences.rb'),
('20260607000000_add_storage_bytes_to_generations.rb'),
('20260607010000_add_not_null_to_uploads_total_image_count.rb');
